### ISSUE TITLE
stroke-width for square icons

### ISSUE THREAD

**Issue by Evolena** [game-icons/icons#189]
The stroke-width looks twice smaller on square icons than on hexa or circle ones. Is it normal?

**Comment by Evolena** [comment]
Also, for hexa and circle icons, the taller the stroke-width is set, the smaller the backgroud size is. Is it intentional?

**Comment by Delapouite** [comment]
You're right. there's currently a discrepancy between background shapes.

In SVG, strokes are always in centered on the path. It means that for the square background, half of the frame width is not displayed, because it's out of bounds (viewBox).

I fixed this behavior for hexa and circle, but still need to apply the same calculation for the square.

**Comment by Delapouite** [comment]
It should be better with the new version of the studio which have been released.

They're still some rounding issue sometimes, but it's a different problem.

**Comment by Evolena** [comment]
It's indeed correct now for the first issue (stroke-width of square background).
However, the second remains for all shapes (the taller the stroke-width is set, the smaller the overall backgroud size is). Do you prefer that I open a new dedicated issue?

**Comment by Evolena** [comment]
Despite these little details, the studio is a wonderful tool :)
