### ISSUE TITLE
Request: add  attribute "id=" into download svg file.

### ISSUE THREAD

**Issue by Dimon-II** [game-icons/icons#385]
Add attribute id="image-name" (current filename) into download svg file. 
This will make it easier to create single file SVG-clipart, like this:
`<defs>`
`<path id="3d-meeple" d="M192..."/>`
`<path id="3d-stairs" d="..."/>`
`<path id="abacus" d="..."/>`
`<path id="abstract-001" ...`

**Comment by Delapouite** [comment]
Hello.

I assume that you use a script to build this kind of SVG sprites, because doing it by hand would be very time consuming and error prone.
Such a script loops over a collection of files in order to aggregate them. Depending on how it is written, adding the id during this phase could be automated by this tool.

**Comment by Dimon-II** [comment]
I made a program that merges the folder of SVG files into one CLIPART file. Looks like this enchatement will add amenities.

**Comment by Delapouite** [comment]
Here's a shell script that should do the job:

```
#!/bin/sh

for icon in $(find . -name '*.svg'); do
  filename=$(basename "$icon")
  id="${filename%.*}"
  sed -i 's/path/path id="'"$id"'"/2' "$icon"
done
```
