### ISSUE TITLE
Label Ku Klux Klan mask

### ISSUE THREAD

**Issue by sinnom** [game-icons/icons#948]
[The icon labeled "cultist"](https://game-icons.net/1x1/skoll/cultist.html) is real world garb of the [Ku Klux Klan](https://en.wikipedia.org/wiki/Ku_Klux_Klan). This icon should be labeled as such so users can make an informed decision of whether they want a symbol of a racist, bigoted hate organization in their game. 

I wouldn't be opposed to its entire removal from the project, though at the very least it shouldn't be in here unlabeled.

**Comment by DarkZaitzev** [comment]
Hello Sinnom, I would like to argue that this identification on the hood as only a symbol of "KKK" is a little to narrow.
This type of hoods have been in use for a lot of time, and the cut on the base could be more identifiable as one of the religious movements on the south of Europe, like Malta. In Spain also there are religious traditions that use this kind of hoods, as many druidic celtic neo-pagan rites use something similar.
The United States history is not the whole world's history, and to take away this symbol because a group of people see an specific symbol instead of a possible more general item used in various religions may seem "advanced" in your country, but it could be perceived as bigoted by others. Although this may seem harsh, I do not seek a confrontation, my intentions are more in the sense of inviting you and others to broaden your history and cultural horizons. This hood belongs to humanity, not a group in particular, do not let this people (the KKK) make our world smaller through fear. 

Cheers and I hope they do not pull down an icon because of censorship...

**Comment by DarkZaitzev** [comment]
In Holy Week, I think in English is Easter Festivities, is used in a lot of places, and even though I am not religious, I think censorship is not the way to go... image taken this from a site that promotes the religious festivities in Spain... and yes they also are right-wing. But not all users are:

[PENITENTES EN SEMANA SANTA](https://cdnb.20m.es/sites/76/2021/03/Algunos-datos-sobre-el-capirote-usado-por-los-penitentes-durante-las-procesiones-de-Semana-Santa.jpg)

About the name in Spanish, etymologically, the term 'capirote' comes from 'capirón' and this from the Latin 'cappero', whose meaning is a "garment that covers the head".

**Comment by sinnom** [comment]
I apologize, I was ignorant of the hood's significance in other contexts. I agree it would not be desirable to rename it. I will close the issue.
